/// <auto-generated/>

namespace Client.Models.DiscordPacket;

public sealed class Handshake
{
    public class RootObject
    {
        public string cmd   { get; set; }
        public Data   data  { get; set; }
        public string evt   { get; set; }
        public object nonce { get; set; }
    }

    public class Data
    {
        public int    v      { get; set; }
        public Config config { get; set; }
        public User   user   { get; set; }
    }

    public class Config
    {
        public string cdn_host     { get; set; }
        public string api_endpoint { get; set; }
        public string environment  { get; set; }
    }

    public class User
    {
        public string                 id                     { get; set; }
        public string                 username               { get; set; }
        public string                 discriminator          { get; set; }
        public string                 global_name            { get; set; }
        public string                 avatar                 { get; set; }
        public Avatar_decoration_data avatar_decoration_data { get; set; }
        public bool                   bot                    { get; set; }
        public int                    flags                  { get; set; }
        public int                    premium_type           { get; set; }
    }

    public class Avatar_decoration_data
    {
        public string asset { get; set; }
        public string skuId { get; set; }
    }
}
